namespace MDKControl.Core.Models
{
    public enum MoCoBusMainCommand : byte
    {
        NoOp = 0,
        Reserved,

        Start,
        Pause,
        Stop,
        DebugLed,
        TimingMaster,
        SetStoredName,
        SetDeviceAddress,
        SetCommonLineForStepPulsing,
        SendAllMotorsToHome,
        SetMotorsMaxStepRate,
        SetAltInputEdge,
        AltAltIoMode,
        SetJoystickWatchdog,
        SetAltOutputBeforeShotDelayTime,
        SetAltOutputAfterShotDelayTime,
        SetAltOutputBeforeShotTime,
        SetAltOutputAfterShotTime,
        SetAltOutputTriggerLevel,
        SetMaxProgramRunTime,
        SetStartProgramDelay,
        SetProgramMode,
        SetJoystickMode,
        SetPingPongFlag,
        SendAllMotorsToProgramStart,
        SetProgramStartPoint,
        SetProgramStopPoint,
        SetFramesPerSecondFlag,
        ReverseAllMotorsStartStopPoints,

        SetGraffikMode = 50,

        GetFirmwareVersion = 100,
        GetRunStatus,
        GetRunTime,
        GetCurrentlyExposing,
        GetTimingMasterValue,
        GetName,
        GetMotorsMaxStepRate,
        GetVoltageReading,
        GetCurrentToMotors,
        GetAltInputEdge,
        GetAltIoMode,
        GetLimitSwitchStatus,
        GetAltOutputBeforeShotDelayTime,
        GetAltOutputAfterShotDelayTime,
        GetAltOutputBeforeShotTime,
        GetAltOutputAfterShotTime,
        GetAltOutputTriggerLevel,
        GetStartProgramDelay,
        GetProgramMode,
        GetControllerPowerCycle,
        GetJoystickMode,
        GetPingPongFlag,
        GetJoystickWatchdogStatus,
        GetProgramPercentComplete,
        GetMotorAttachment,
        GetTotalProgramRunTime,
        GetProgramComplete,
        GetFramesPerSecondFlag,
        GetAllMotorsRunStatus,
        GetValidateProgram,
        GetSleepStateOfAllMotors,

        GetGraffikMode = 150
    }
}