namespace MDKControl.Core.Models
{
    public enum MoCoBusMotorCommand : byte
    {
        NoOp = 0,
        Reserved,

        SetMotorSleep,
        SetMotorEnable,
        StopMotorNow,
        SetBacklashSteps,
        SetMicrostepValue,
        SetMotorMaxStepSpeed,
        SetDirection,
        SetHomeLimitHere,
        SetEndLimitHere,
        SendMotorToHomeLimit,
        SendMotorToEndLimit,
        SetContinuousSpeed,
        SetContinuousMotionAccelDecelRate,
        ExecuteSimpleMove,
        SetProgramStartPoint,
        SetProgramStopPoint,
        SetEasingMode,
        SetLeadInShotsOrTime,
        SetTravelShotsOrTime,
        SetProgramAccel,
        SetProgramDecel,
        SendMotorToProgramStartPoint,
        SendMotorToProgramStopPoint,
        SetLeadOutShotsOrTime,
        ResetLimitsAndProgramStartStopPositions = 27,
        AutoSetProgramMicrosteps,
        SetStartHere,
        SetStopHere,

        GetMotorEnable = 100,
        GetBacklashSteps,
        GetMicrostepValue,
        GetDirection,
        GetMotorMaxStepSpeed,
        GetEndLimitPosition,
        GetCurrentMotorPosition,
        GetMotorRunning,
        GetContinuousSpeed,
        GetContinuousMotionAccelDecelRate,
        GetEasingMode,
        GetProgramStartPoint,
        GetProgramStopPoint,
        GetTravelShotsOrTime,
        GetLeadInShotsOrTime,
        GetProgramAccel,
        GetProgramDecel,
        GetMotorSleepState,
        GetMotorSpeedLimit,
        GetLeadOutShotsOrTime
    }
}