#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MDKControl.Droid.Resource", IsApplication=true)]

namespace MDKControl.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::MDKControl.Droid.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::MDKControl.Droid.Resource.String.Hello;
			global::Reactive.Bindings.Resource.String.ApplicationName = global::MDKControl.Droid.Resource.String.ApplicationName;
			global::Reactive.Bindings.Resource.String.Hello = global::MDKControl.Droid.Resource.String.Hello;
			global::Robotics.Mobile.Core.Resource.String.library_name = global::MDKControl.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int Cancel = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int Close = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int ConnectSwitch = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int ConnectedFragmentContainer = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int ConnectedLayout = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int ConnectingLayout = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int DevicesList = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int DisconnectedLayout = 2131165186;
			
			// aapt resource value: 0x7f070032
			public const int DurationTime = 2131165234;
			
			// aapt resource value: 0x7f070018
			public const int ElapsedShots = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int ElapsedTime = 2131165207;
			
			// aapt resource value: 0x7f070029
			public const int ExposureTime = 2131165225;
			
			// aapt resource value: 0x7f070034
			public const int Hours = 2131165236;
			
			// aapt resource value: 0x7f07000a
			public const int Hundred = 2131165194;
			
			// aapt resource value: 0x7f070037
			public const int Hundredths = 2131165239;
			
			// aapt resource value: 0x7f070031
			public const int IntervalTime = 2131165233;
			
			// aapt resource value: 0x7f07000f
			public const int Joystick = 2131165199;
			
			// aapt resource value: 0x7f070033
			public const int MaxShots = 2131165235;
			
			// aapt resource value: 0x7f070035
			public const int Minutes = 2131165237;
			
			// aapt resource value: 0x7f07000c
			public const int One = 2131165196;
			
			// aapt resource value: 0x7f07001c
			public const int OverallShots = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int OverallTime = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int PanSize = 2131165217;
			
			// aapt resource value: 0x7f07001f
			public const int PanStartPos = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int PanStopPos = 2131165216;
			
			// aapt resource value: 0x7f070012
			public const int Pause = 2131165202;
			
			// aapt resource value: 0x7f07002a
			public const int PostDelayTime = 2131165226;
			
			// aapt resource value: 0x7f070028
			public const int PreDelayTime = 2131165224;
			
			// aapt resource value: 0x7f070016
			public const int Progress = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int RemainingShots = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int RemainingTime = 2131165209;
			
			// aapt resource value: 0x7f070011
			public const int Resume = 2131165201;
			
			// aapt resource value: 0x7f070038
			public const int ScanningStart = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int ScanningStop = 2131165241;
			
			// aapt resource value: 0x7f070036
			public const int Seconds = 2131165238;
			
			// aapt resource value: 0x7f070007
			public const int SetModeAstro = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int SetModePano = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int SetModeSms = 2131165189;
			
			// aapt resource value: 0x7f07001d
			public const int SetRefStart = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int SetRefStop = 2131165214;
			
			// aapt resource value: 0x7f070025
			public const int SetStart = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int SetStop = 2131165222;
			
			// aapt resource value: 0x7f070010
			public const int Slider = 2131165200;
			
			// aapt resource value: 0x7f07002f
			public const int SliderStartPos = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int SliderStopPos = 2131165232;
			
			// aapt resource value: 0x7f07002b
			public const int StartProgram = 2131165227;
			
			// aapt resource value: 0x7f070014
			public const int StartProgramNorth = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int StartProgramSouth = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int Stop = 2131165203;
			
			// aapt resource value: 0x7f070027
			public const int SwapStartStop = 2131165223;
			
			// aapt resource value: 0x7f07000b
			public const int Ten = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int Thousand = 2131165193;
			
			// aapt resource value: 0x7f070024
			public const int TiltSize = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int TiltStartPos = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int TiltStopPos = 2131165219;
			
			// aapt resource value: 0x7f07002c
			public const int VideoLength24 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int VideoLength25 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int VideoLength30 = 2131165230;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DeviceListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeviceView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int IntegerView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int JoystickView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ModeAstroStatusView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ModeAstroView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ModePanoStatusView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ModePanoView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ModeSmsStatusView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ModeSmsView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Splash = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TimeView = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int DeviceListOptionsMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
