#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MDKControl.Droid.Resource", IsApplication=true)]

namespace MDKControl.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::MDKControl.Droid.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::MDKControl.Droid.Resource.String.Hello;
			global::Reactive.Bindings.Resource.String.ApplicationName = global::MDKControl.Droid.Resource.String.ApplicationName;
			global::Reactive.Bindings.Resource.String.Hello = global::MDKControl.Droid.Resource.String.Hello;
			global::Robotics.Mobile.Core.Resource.String.library_name = global::MDKControl.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int ConnectSwitch = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int ConnectedLayout = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int ConnectingLayout = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int DevicesList = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int DisconnectedLayout = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int Joystick = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int MinutesPicker = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int PauseProgram = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int ScanningStart = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int ScanningStop = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int SecondsPicker = 2131165202;
			
			// aapt resource value: 0x7f070007
			public const int SetModeAstro = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int SetModePano = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int SetModeSms = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int SetRefStart = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int SetRefStop = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int SetStart = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int SetStop = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int StartProgram = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int StopProgram = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int SwapStartStop = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DeviceListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeviceView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NumberPickerDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RunningView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Splash = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int DeviceListOptionsMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
